[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "haskellian-either"
version = "0.1.4"
authors = [
  {name="Marcel Claramunt", email="marcel@moveread.com"}
]
description = "Simple Either type"
dependencies = []
requires-python = ">=3.10"
readme = {file="README.md", content-type="text/markdown"}

# [project.urls]
# repo = "<GIT_REPO_URL>"

[project.optional-dependencies]
pydantic = ["pydantic"]
# test = [
#   "pytest < 5.0.0",
#   "pytest-cov[all]"
# ]